/*
 * The MIT License
 *
 * Copyright 2026 Viktor Alexander Hartung.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.hartrusion.modeling.phasedfluid;

/**
 * Models a tubine stage using isentropic expansion of the fluid. Due to the 
 * nature of the phased fluid model, this is not as accurate as expected but 
 * does generate some results.
 *
 * @author Viktor Alexander Hartung
 */
public class PhasedTurbineStage
        
extends PhasedAbstractFlowResistance {

    private final PhasedFluidProperties fluidProperties;

    public PhasedTurbineStage(PhasedFluidProperties fluidProperties) {
        this.fluidProperties = fluidProperties;
        this.phasedHandler = new PhasedIsentropicExpansionHandler(this);
    }

    @Override
    public PhasedFluidProperties getPhasedFluidProperties() {
        return fluidProperties;
    }

    public void setIsentropicFactor(double k) {
        ((PhasedIsentropicExpansionHandler) phasedHandler).setIsentropicFactor(k);
    }

    /**
     * Get the excess specific energy that was consumed by the turbine (converted to work).
     * @return value in J/kg
     */
    public double getExcessHeatEnergy() {
        return ((PhasedIsentropicExpansionHandler) phasedHandler).getExcessEnergy();
    }

    /**
     * Get the mechanical power generated by this turbine stage.
     * @return value in J/s = Watts
     */
    public double getExcessPower() {
        return getExcessHeatEnergy() * Math.abs(getFlow());
    }
}