/*
 * The MIT License
 *
 * Copyright 2026 Viktor Alexander Hartung.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.hartrusion.modeling.assemblies;

import com.hartrusion.modeling.heatfluid.HeatFlowSource;
import com.hartrusion.modeling.heatfluid.HeatNode;
import com.hartrusion.modeling.heatfluid.HeatOrigin;
import com.hartrusion.modeling.solvers.DomainAnalogySolver;
import com.hartrusion.util.SimpleLogOut;
import static org.testng.Assert.*;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

/**
 *
 * @author Viktor Alexander Hartung
 */
public class HeatExchangerNoMassTest {

    /*
    *       ------                ------
    *      _|_   |               _|_   |
    *   priSink  |            secSink  |
    *            o                     o      Nodes are generated by the 
    *            |                     |      assembly class, here: out nodes
    *           ===                   ===
    *           | |                   | |
    *           | | Primary Side      | | Secondary Side
    *           | |                   | |
    *           | |- Connection via  -| |
    *           | |-both heat handlers| |
    *           | |                   | |
    *           | |                   | |
    *           ===                   ===
    *            |                     |
    *            o                     o - also part of assembly class (in node)
    *            |                     |
    *           (-) priFlow           (-) secFlow
    *            |                     |
    *            o priSrcNode          o secSrcNode
    *            |                     |
    *            |                     |
    *           _|_ priSrc            _|_ secSrc
     */
    private HeatExchangerNoMass instance;

    private HeatOrigin priSrc, secSrc, priSink, secSink;
    private HeatNode priSrcNode, secSrcNode;
    private HeatFlowSource priFlow, secFlow;

    private DomainAnalogySolver solver;

    @BeforeClass
    public static void setUpClass() throws Exception {
        // Keep Log out clean during test run
        SimpleLogOut.configureLoggingWarningsOnly();
    }

    @BeforeMethod
    public void setUpMethod() throws Exception {
        // Set up the network as displayed on the comment and set up a solver.
        instance = new HeatExchangerNoMass();
        priSrc = new HeatOrigin();
        secSrc = new HeatOrigin();
        priSink = new HeatOrigin();
        secSink = new HeatOrigin();
        priSrcNode = new HeatNode();
        secSrcNode = new HeatNode();
        priFlow = new HeatFlowSource();
        secFlow = new HeatFlowSource();

        instance.initGenerateNodes();
        instance.initName("HeatExchanger");
        priSrc.setName("priSrc");
        secSrc.setName("secSrc");
        priSink.setName("priSink");
        secSink.setName("secSink");
        priSrcNode.setName("priSrcNode");
        secSrcNode.setName("secSrcNode");
        priFlow.setName("priFlow");
        secFlow.setName("secFlow");

        // Set NTU value
        instance.initCharacteristic(0.8);

        // Connect elements:
        priSrc.connectToVia(priFlow, priSrcNode);
        priFlow.connectTo(instance.getHeatNode(
                HeatExchangerNoMass.PRIMARY_IN));
        priSink.connectTo(instance.getHeatNode(
                HeatExchangerNoMass.PRIMARY_OUT));
        secSrc.connectToVia(secFlow, secSrcNode);
        secFlow.connectTo(instance.getHeatNode(
                HeatExchangerNoMass.SECONDARY_IN));
        secSink.connectTo(instance.getHeatNode(
                HeatExchangerNoMass.SECONDARY_OUT));

        // Set up solver
        solver = new DomainAnalogySolver();
        solver.addNetwork(priSrcNode);
    }

    @AfterMethod
    public void tearDownMethod() throws Exception {
        instance = null;
        priSrc = null;
        secSrc = null;
        priSink = null;
        secSink = null;
        priSrcNode = null;
        secSrcNode = null;
        priFlow = null;
        secFlow = null;
        solver = null;
    }

    /**
     * No flow: Nothing happens.
     */
    @Test
    public void testZeroFlow() {
        priFlow.setFlow(0.0);
        secFlow.setFlow(0.0);

        solver.prepareCalculation();
        solver.doCalculation();

        assertEquals(priSink.isCalculationFinished(), true);
        assertEquals(secSink.isCalculationFinished(), true);
        assertEquals(instance.getPrimarySide().isCalculationFinished(), true);
        assertEquals(instance.getSecondarySide().isCalculationFinished(), true);
        assertEquals(instance.getPrimarySide().getFlow(), 0.0, 1e-12);
        assertEquals(instance.getSecondarySide().getFlow(), 0.0, 1e-12);
    }

    /**
     * Two streams with same temperature and mass flow
     */
    @Test
    public void equalFlowsAndTemperatures() {
        priFlow.setFlow(20.0);
        priSrc.setOriginTemperature(300);
        secFlow.setFlow(20.0);
        secSrc.setOriginTemperature(300);

        solver.prepareCalculation();
        solver.doCalculation();

        assertEquals(priSink.isCalculationFinished(), true);
        assertEquals(secSink.isCalculationFinished(), true);
        assertEquals(instance.getPrimarySide().isCalculationFinished(), true);
        assertEquals(instance.getSecondarySide().isCalculationFinished(), true);

        // Flow rates and temperature must be same as before
        assertEquals(instance.getPrimarySide().getFlow(), 20.0, 1e-12);
        assertEquals(instance.getSecondarySide().getFlow(), 20.0, 1e-12);
        assertEquals(instance.getHeatNode(HeatExchangerNoMass.PRIMARY_IN)
                .getTemperature(), 300, 1e-12);
        assertEquals(instance.getHeatNode(HeatExchangerNoMass.SECONDARY_OUT)
                .getTemperature(), 300, 1e-12);
        assertEquals(secSink.isCalculationFinished(), true);
    }

    /**
     * Two streams with same temperature but different mass flow, there must be
     * no difference in temperatures.
     */
    @Test
    public void differentFlowsAndEqualTemperatures() {
        priFlow.setFlow(20.0);
        priSrc.setOriginTemperature(300);
        secFlow.setFlow(50.0);
        secSrc.setOriginTemperature(300);

        solver.prepareCalculation();
        solver.doCalculation();

        assertEquals(priSink.isCalculationFinished(), true);
        assertEquals(secSink.isCalculationFinished(), true);
        assertEquals(instance.getPrimarySide().isCalculationFinished(), true);
        assertEquals(instance.getSecondarySide().isCalculationFinished(), true);

        // Flow rates and temperature must be same as before
        assertEquals(instance.getPrimarySide().getFlow(), 20.0, 1e-12);
        assertEquals(instance.getSecondarySide().getFlow(), 50.0, 1e-12);
        assertEquals(instance.getHeatNode(HeatExchangerNoMass.PRIMARY_IN)
                .getTemperature(), 300, 1e-12);
        assertEquals(instance.getHeatNode(HeatExchangerNoMass.SECONDARY_OUT)
                .getTemperature(), 300, 1e-12);
    }

    /**
     * Sets a fixed flow rate of 20 kg/s and goes from 4 to 496 kg/s on the
     * other side with some temperature difference.
     */
    @Test
    public void equalFlowsAndDifferentTemperatures() {
        for (int idx = 4; idx < 500; idx = idx + 4) {
            priFlow.setFlow((double) idx);
            priSrc.setOriginTemperature(400);
            secFlow.setFlow(20.0);
            secSrc.setOriginTemperature(300);

            solver.prepareCalculation();
            solver.doCalculation();

            assertEquals(priSink.isCalculationFinished(), true);
            assertEquals(secSink.isCalculationFinished(), true);
            assertEquals(instance.getPrimarySide().isCalculationFinished(), 
                    true);
            assertEquals(instance.getSecondarySide().isCalculationFinished(), 
                    true);

            // Dunno how to test this but i looked at the print out of this 
            // here.
            /*
            System.out.println(
                    "Pri flow: "
                    + String.format("%03.2f", (double) priFlow.getFlow())
                    + " kg/s, Pri Out: "
                    + String.format("%03.2f", instance.getHeatNode(HeatExchangerNoMass.PRIMARY_OUT)
                            .getTemperature())
                    + ", Sec Out: "
                    + String.format("%03.2f", instance.getHeatNode(HeatExchangerNoMass.SECONDARY_OUT)
                            .getTemperature()));
            */
            // check for valid temperature ranges at least
            assertEquals(instance.getHeatNode(HeatExchangerNoMass.PRIMARY_OUT)
                            .getTemperature() <= 400, true);
            assertEquals(instance.getHeatNode(HeatExchangerNoMass.PRIMARY_OUT)
                            .getTemperature() >= 300, true);
            assertEquals(instance.getHeatNode(HeatExchangerNoMass.PRIMARY_OUT)
                            .getTemperature() <= 400, true);
            assertEquals(instance.getHeatNode(HeatExchangerNoMass.PRIMARY_OUT)
                            .getTemperature() >= 300, true);
        }
    }
}
